### ISSUE TITLE
How to run a file?

### ISSUE THREAD

**Issue by wintkhantlin** [ensatone/Chocolat#1]
I tired to run
```bash
> a.exe 
> a.exe main.chocolat
>chocolat.exe
>chocolat.exe main.chocolat 
```

I am on windows 11

**Comment by ensatone** [comment]
> I tired to run
> 
> ```shell
> > a.exe 
> > a.exe main.chocolat
> >chocolat.exe
> >chocolat.exe main.chocolat 
> ```
> 
> I am on windows 11

Firstly, you need to download io language from https://iolanguage.org/ for your respective OS and extract everything into chocolat-core folder... And open the terminal or command prompt with the path to the said chocolat-core folder and main.chocolat must also be in the chocolat-core folder... Then, compile the main.chocolat file by using the command, "io chocolatc.io" and it will produce the main.ccl and *.ccl files... Then, if you use the command, "chocolat" in Windows or "./chocolat" in linux, it will read the *.ccl files and give you the output.

**Comment by wintkhantlin** [comment]
So i need to change *. chocolate to *ccl?

**Comment by wintkhantlin** [comment]
If you add command line arguments it will be better

**Comment by ensatone** [comment]
You don't need to change .chocolat file to .ccl You just need to execute the chocolatc.io file by using the command "io chocolatc.io" This will generate .ccl files... And you just run the program(.ccl files) by using the command "chocolat" or "./chocolat" in linux... I made this programming language to share my language design and compiler architectures... This is not fully commercial language but just an example language... There are programming languages which are based on greatly optimized compilers and interpreters... I am moving onto that part
